"""Define __tablename__ for MeetingParticipant and rename unique constraint

Revision ID: 0c6189c1cdf9
Revises: fa34ce78915d
Create Date: 2024-10-13 20:57:05.241573

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0c6189c1cdf9'
down_revision = 'fa34ce78915d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting_participants',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('meeting_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('raci_role_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['meeting_id'], ['meeting.id'], ),
        sa.ForeignKeyConstraint(['raci_role_id'], ['raci_role.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('meeting_id', 'user_id', name='uix_meeting_participants_meeting_id_user_id')
    )
    op.drop_table('meeting_participant')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting_participant',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('meeting_id', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('raci_role_id', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(['meeting_id'], ['meeting.id'], name='meeting_participant_meeting_id_fkey'),
        sa.ForeignKeyConstraint(['raci_role_id'], ['raci_role.id'], name='meeting_participant_raci_role_id_fkey'),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='meeting_participant_user_id_fkey'),
        sa.PrimaryKeyConstraint('id', name='meeting_participant_pkey'),
        sa.UniqueConstraint('meeting_id', 'user_id', name='uix_meeting_user')
    )
    op.drop_table('meeting_participants')
    # ### end Alembic commands ###