"""Added active hub to user

Revision ID: 199e09ac8b56
Revises: 86ea88e0a965
Create Date: 2024-08-20 10:50:03.703167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '199e09ac8b56'
down_revision = '86ea88e0a965'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_meeting_hub_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'meeting_hub', ['active_meeting_hub_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('active_meeting_hub_id')

    # ### end Alembic commands ###
