"""Add recurring_event_id and is_recurring to meetings 3

Revision ID: 1fad472916a2
Revises: ea68111539a2
Create Date: 2024-10-07 23:08:07.515980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fad472916a2'
down_revision = 'ea68111539a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meeting_hub_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'meeting_hub', ['meeting_hub_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('meeting_hub_id')

    # ### end Alembic commands ###
