"""Add title and sorting_id to ActionItem

Revision ID: 1fe65f02e979
Revises: 65bf60f48eb0
Create Date: 2024-09-21 00:39:39.537179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fe65f02e979'
down_revision = '65bf60f48eb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=255), nullable=False, server_default='Untitled'))
        batch_op.add_column(sa.Column('sorting_id', sa.Integer(), nullable=False, server_default="0"))
        batch_op.drop_column('summary')

    # Remove server default after existing rows are updated
    op.alter_column('action_item', 'title', server_default=None)
    op.alter_column('action_item', 'sorting_id', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_column('sorting_id')
        batch_op.drop_column('title')
    # ### end Alembic commands ###