"""Update Meeting and MeetingHub for many-to-many relationship

Revision ID: 2cffa5813d5a
Revises: 6bf746d5dadc
Create Date: 2024-10-22 23:12:00.048643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cffa5813d5a'
down_revision = '6bf746d5dadc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('raci_role_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meeting.id'], ),
    sa.ForeignKeyConstraint(['raci_role_id'], ['raci_role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id', 'user_id', name='uix_meeting_user')
    )
    with op.batch_alter_table('meeting_meetinghub', schema=None) as batch_op:
        batch_op.create_unique_constraint('uix_meeting_meetinghub', ['meeting_id', 'meeting_hub_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting_meetinghub', schema=None) as batch_op:
        batch_op.drop_constraint('uix_meeting_meetinghub', type_='unique')

    op.drop_table('meeting_participants')
    # ### end Alembic commands ###
