"""Add name to MeetingSession model

Revision ID: 39ccba70ec1c
Revises: c81ff054e9bd
Create Date: 2024-08-18 07:13:20.496347

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '39ccba70ec1c'
down_revision = 'c81ff054e9bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=256), nullable=True))

    # Set a default name for existing rows
    op.execute("""
        UPDATE meeting_session 
        SET name = 'Unnamed Session ' || id 
        WHERE name IS NULL
    """)

    # Alter the column to make it non-nullable
    with op.batch_alter_table('meeting_session', schema=None) as batch_op:
        batch_op.alter_column('name', nullable=False)
        batch_op.alter_column('meeting_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('recording', schema=None) as batch_op:
        batch_op.alter_column('concatenation_file_name',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recording', schema=None) as batch_op:
        batch_op.alter_column('concatenation_file_name',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)

    with op.batch_alter_table('meeting_session', schema=None) as batch_op:
        batch_op.alter_column('meeting_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('name')

    # ### end Alembic commands ###