"""Add summary, description, and status to ActionItem

Revision ID: 3d41ce810966
Revises: 0e80dfe5a1a1
Create Date: 2024-09-17 20:32:01.267665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d41ce810966'
down_revision = '0e80dfe5a1a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action_item', schema=None) as batch_op:
        batch_op.alter_column('summary',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.Text(),
               existing_nullable=False,
               existing_server_default=sa.text("'No summary'::character varying"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action_item', schema=None) as batch_op:
        batch_op.alter_column('summary',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False,
               existing_server_default=sa.text("'No summary'::character varying"))

    # ### end Alembic commands ###
