"""Add recurring_event_id and is_recurring to meetings making false

Revision ID: 4c90a0f4b2d4
Revises: 1fad472916a2
Create Date: 2024-10-07 23:24:05.623756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c90a0f4b2d4'
down_revision = '1fad472916a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting', schema=None) as batch_op:
        batch_op.alter_column('meeting_hub_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting', schema=None) as batch_op:
        batch_op.alter_column('meeting_hub_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
