"""Add recurring_event_id and is_recurring to meetings

Revision ID: 539d14dd0b67
Revises: 4d80df31505d
Create Date: 2024-10-07 22:43:22.669901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '539d14dd0b67'
down_revision = '4d80df31505d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recurring_event_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.create_unique_constraint(None, ['recurring_event_id'])
        batch_op.drop_constraint('meeting_meeting_hub_id_fkey', type_='foreignkey')
        batch_op.drop_column('meeting_hub_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meeting_hub_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('meeting_meeting_hub_id_fkey', 'meeting_hub', ['meeting_hub_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('description',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
        batch_op.drop_column('created_at')
        batch_op.drop_column('recurring_event_id')

    # ### end Alembic commands ###
