"""Establish many-to-many relationship between Meeting and MeetingHub

Revision ID: 5eea52a414c8
Revises: 2cffa5813d5a
Create Date: 2024-10-22 23:24:30.514503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5eea52a414c8'
down_revision = '2cffa5813d5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the association table if it doesn't exist
    op.create_table(
        'meeting_meetinghub',
        sa.Column('meeting_id', sa.Integer(), nullable=False),
        sa.Column('meeting_hub_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['meeting_id'], ['meeting.id'], ),
        sa.ForeignKeyConstraint(['meeting_hub_id'], ['meeting_hub.id'], ),
        sa.PrimaryKeyConstraint('meeting_id', 'meeting_hub_id'),
        sa.UniqueConstraint('meeting_id', 'meeting_hub_id', name='uix_meeting_meetinghub')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meeting_meetinghub')
    # ### end Alembic commands ###