"""Add many-to-many relationship between User and Company

Revision ID: 6477f5fd8c90
Revises: 856e732bdbd6
Create Date: 2024-11-05 22:58:43.047279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6477f5fd8c90'
down_revision = '856e732bdbd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_company_association',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'company_id'),
    sa.UniqueConstraint('user_id', 'company_id', name='uix_user_company_association')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_company_association')
    # ### end Alembic commands ###
