"""Fix lazy loader on UserRoleAssignment.hub relationship

Revision ID: 6b4410788666
Revises: 847569e32eb3
Create Date: 2024-10-15 23:03:40.747732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b4410788666'
down_revision = '847569e32eb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting_hub', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=False, server_default='1'))  # Assign a default user ID (adjust to your scenario)
        batch_op.add_column(sa.Column('admin_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['created_by'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['admin_id'], ['id'])
    
    # After adding the column, remove the server_default
    op.alter_column('meeting_hub', 'created_by', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting_hub', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('admin_id')
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###
