"""Update Meeting and MeetingHub for many-to-many relationship

Revision ID: 6bf746d5dadc
Revises: c9320b86a38e
Create Date: 2024-10-22 22:41:15.754845

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6bf746d5dadc'
down_revision = 'c9320b86a38e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting_meetinghub',
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('meeting_hub_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_hub_id'], ['meeting_hub.id'], ),
    sa.ForeignKeyConstraint(['meeting_id'], ['meeting.id'], ),
    sa.PrimaryKeyConstraint('meeting_id', 'meeting_hub_id'),
    sa.UniqueConstraint('meeting_id', 'meeting_hub_id', name='uix_meeting_meetinghub')
    )
    op.drop_table('meeting_participants')
    with op.batch_alter_table('meeting', schema=None) as batch_op:
        batch_op.drop_constraint('meeting_recurring_event_id_key', type_='unique')
        batch_op.create_index(batch_op.f('ix_meeting_recurring_event_id'), ['recurring_event_id'], unique=True)
        batch_op.drop_constraint('meeting_meeting_hub_id_fkey', type_='foreignkey')
        batch_op.drop_column('meeting_hub_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meeting_hub_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('meeting_meeting_hub_id_fkey', 'meeting_hub', ['meeting_hub_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_meeting_recurring_event_id'))
        batch_op.create_unique_constraint('meeting_recurring_event_id_key', ['recurring_event_id'])

    op.create_table('meeting_participants',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('meeting_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('raci_role_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meeting.id'], name='meeting_participants_meeting_id_fkey'),
    sa.ForeignKeyConstraint(['raci_role_id'], ['raci_role.id'], name='meeting_participants_raci_role_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='meeting_participants_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='meeting_participants_pkey'),
    sa.UniqueConstraint('meeting_id', 'user_id', name='uix_meeting_user')
    )
    op.drop_table('meeting_meetinghub')
    # ### end Alembic commands ###
