"""Use back_populates to fix relationship conflict between MeetingHub and UserRoleAssignment

Revision ID: 7be08e6a2735
Revises: 0c6189c1cdf9
Create Date: 2024-10-13 21:02:33.418146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7be08e6a2735'
down_revision = '0c6189c1cdf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting_participants', schema=None) as batch_op:
        batch_op.drop_constraint('uix_meeting_participants_meeting_id_user_id', type_='unique')
        batch_op.create_unique_constraint('uix_meeting_user', ['meeting_id', 'user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting_participants', schema=None) as batch_op:
        batch_op.drop_constraint('uix_meeting_user', type_='unique')
        batch_op.create_unique_constraint('uix_meeting_participants_meeting_id_user_id', ['meeting_id', 'user_id'])

    # ### end Alembic commands ###
