"""Add audio_url column to MeetingSession

Revision ID: 7ff7d4534e70
Revises: 199e09ac8b56
Create Date: 2024-08-23 23:01:39.925343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ff7d4534e70'
down_revision = '199e09ac8b56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('audio_url', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting_session', schema=None) as batch_op:
        batch_op.drop_column('audio_url')

    # ### end Alembic commands ###
