"""Add sso_platform to User model

Revision ID: 856e732bdbd6
Revises: feaa79ff5120
Create Date: 2024-10-28 20:05:29.284007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '856e732bdbd6'
down_revision = 'feaa79ff5120'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sso_platform', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('sso_platform')

    # ### end Alembic commands ###
