"""Add name to Meedd user id to meeting levels

Revision ID: 86ea88e0a965
Revises: 39ccba70ec1c
Create Date: 2024-08-18 13:42:03.734467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86ea88e0a965'
down_revision = '39ccba70ec1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_meeting',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meeting.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'meeting_id')
    )
    op.create_table('user_meeting_session',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('meeting_session_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_session_id'], ['meeting_session.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'meeting_session_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_meeting_session')
    op.drop_table('user_meeting')
    # ### end Alembic commands ###
