"""Add user_type and inter_user_role columns

Revision ID: 8d295e05de28
Revises: 7ff7d4534e70
Create Date: 2024-09-09 13:30:00.106233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d295e05de28'
down_revision = '7ff7d4534e70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        # Set server default to 'external' for user_type
        batch_op.add_column(sa.Column('user_type', sa.String(length=20), nullable=False, server_default='external'))
        batch_op.add_column(sa.Column('internal_user_role', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('internal_user_role')
        batch_op.drop_column('user_type')

    # ### end Alembic commands ###