"""Add Microsoft OAuth token fields to User model

Revision ID: cee1da22eba1
Revises: d6761be5ae71
Create Date: 2024-10-23 22:53:01.047089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cee1da22eba1'
down_revision = 'd6761be5ae71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('microsoft_oauth_token', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('microsoft_refresh_token', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('microsoft_token_expires_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('microsoft_token_expires_at')
        batch_op.drop_column('microsoft_refresh_token')
        batch_op.drop_column('microsoft_oauth_token')

    # ### end Alembic commands ###
