"""Revert database to match commit 2b340f81

Revision ID: d6761be5ae71
Revises: e915f430f02d
Create Date: 2024-10-23 20:49:18.243017

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd6761be5ae71'
down_revision = 'e915f430f02d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meeting_meetinghub')

    # Insert a default meeting_hub entry with id=1 to avoid FK constraint issues
    # Adjust the `company_id` and `created_by` to appropriate default values (set it as 1 or any valid company_id and created_by)
    op.execute("""
        INSERT INTO meeting_hub (id, name, company_id, created_by)
        VALUES (1, 'Default Hub', 1, 1)  -- Use valid company_id and user_id for created_by
        ON CONFLICT DO NOTHING
    """)

    # Modify the meeting table
    with op.batch_alter_table('meeting', schema=None) as batch_op:
        # Step 1: Add meeting_hub_id column as nullable=True
        batch_op.add_column(sa.Column('meeting_hub_id', sa.Integer(), nullable=True))
    
    # Step 2: Perform the update to set default values for meeting_hub_id
    op.execute('UPDATE meeting SET meeting_hub_id = 1 WHERE meeting_hub_id IS NULL')  # Set this to the inserted default hub

    # Step 3: Alter the meeting_hub_id column to be NOT NULL
    with op.batch_alter_table('meeting', schema=None) as batch_op:
        batch_op.alter_column('meeting_hub_id', nullable=False)

        # Modify the visibility column type
        batch_op.alter_column('visibility',
            existing_type=postgresql.ENUM('ALL_HUB_MEMBERS', 'PARTICIPANTS', 'PRIVATE', 'PUBLIC', 'CONFIDENTIAL', 'DEFAULT', name='visibilitysettings'),
            type_=sa.String(length=32),
            existing_nullable=False)

        # Remove the index on recurring_event_id and create a unique constraint
        batch_op.drop_index('ix_meeting_recurring_event_id')
        batch_op.create_unique_constraint(None, ['recurring_event_id'])

        # Create a foreign key constraint on meeting_hub_id
        batch_op.create_foreign_key(None, 'meeting_hub', ['meeting_hub_id'], ['id'])

    # Modify the user_meeting_hub table
    with op.batch_alter_table('user_meeting_hub', schema=None) as batch_op:
        batch_op.drop_column('visibility_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Reverse the user_meeting_hub table changes
    with op.batch_alter_table('user_meeting_hub', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visibility_status', postgresql.ENUM('VIEWER', 'EDITOR', 'ADMIN', name='visibilitystatus'), autoincrement=False, nullable=False))

    # Reverse the meeting table changes
    with op.batch_alter_table('meeting', schema=None) as batch_op:
        # Drop the foreign key constraint and unique constraint
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')

        # Recreate the index on recurring_event_id
        batch_op.create_index('ix_meeting_recurring_event_id', ['recurring_event_id'], unique=True)

        # Revert the visibility column type change
        batch_op.alter_column('visibility',
            existing_type=sa.String(length=32),
            type_=postgresql.ENUM('ALL_HUB_MEMBERS', 'PARTICIPANTS', 'PRIVATE', 'PUBLIC', 'CONFIDENTIAL', 'DEFAULT', name='visibilitysettings'),
            existing_nullable=False)

        # Drop the meeting_hub_id column
        batch_op.drop_column('meeting_hub_id')

    # Recreate the meeting_meetinghub association table
    op.create_table('meeting_meetinghub',
        sa.Column('meeting_id', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('meeting_hub_id', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(['meeting_hub_id'], ['meeting_hub.id'], name='meeting_meetinghub_meeting_hub_id_fkey'),
        sa.ForeignKeyConstraint(['meeting_id'], ['meeting.id'], name='meeting_meetinghub_meeting_id_fkey'),
        sa.UniqueConstraint('meeting_id', 'meeting_hub_id', name='uix_meeting_meetinghub')
    )
    # ### end Alembic commands ###