"""Add meeting participants relationship and other updates

Revision ID: fa34ce78915d
Revises: 4c90a0f4b2d4
Create Date: 2024-10-13 20:45:46.746150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa34ce78915d'
down_revision = '4c90a0f4b2d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raci_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('hierarchy_level', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meeting_participant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('raci_role_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meeting.id'], ),
    sa.ForeignKeyConstraint(['raci_role_id'], ['raci_role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id', 'user_id', name='uix_meeting_user')
    )
    op.create_table('user_role_assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('hub_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.ForeignKeyConstraint(['hub_id'], ['meeting_hub.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', 'department_id', 'hub_id', name='uix_user_role_scope')
    )
    op.drop_table('user_meeting')
    with op.batch_alter_table('user_meeting_hub', schema=None) as batch_op:
        batch_op.drop_constraint('user_meeting_hub_user_id_meeting_hub_id_key', type_='unique')
        batch_op.create_unique_constraint('uix_user_meeting_hub', ['user_id', 'meeting_hub_id'])

    with op.batch_alter_table('user_meeting_session', schema=None) as batch_op:
        batch_op.drop_constraint('user_meeting_session_user_id_meeting_session_id_key', type_='unique')
        batch_op.create_unique_constraint('uix_user_meeting_session', ['user_id', 'meeting_session_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_meeting_session', schema=None) as batch_op:
        batch_op.drop_constraint('uix_user_meeting_session', type_='unique')
        batch_op.create_unique_constraint('user_meeting_session_user_id_meeting_session_id_key', ['user_id', 'meeting_session_id'])

    with op.batch_alter_table('user_meeting_hub', schema=None) as batch_op:
        batch_op.drop_constraint('uix_user_meeting_hub', type_='unique')
        batch_op.create_unique_constraint('user_meeting_hub_user_id_meeting_hub_id_key', ['user_id', 'meeting_hub_id'])

    op.create_table('user_meeting',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('meeting_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meeting.id'], name='user_meeting_meeting_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_meeting_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'meeting_id', name='user_meeting_pkey'),
    sa.UniqueConstraint('user_id', 'meeting_id', name='user_meeting_user_id_meeting_id_key')
    )
    op.drop_table('user_role_assignment')
    op.drop_table('meeting_participant')
    op.drop_table('role')
    op.drop_table('department')
    op.drop_table('raci_role')
    # ### end Alembic commands ###
