"""added msft oauth

Revision ID: feaa79ff5120
Revises: cee1da22eba1
Create Date: 2024-10-25 07:40:01.874999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'feaa79ff5120'
down_revision = 'cee1da22eba1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('user_type')
        batch_op.drop_column('internal_user_role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('internal_user_role', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('user_type', sa.VARCHAR(length=20), server_default=sa.text("'external'::character varying"), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
